### ISSUE TITLE
Cant set video mode

### ISSUE THREAD

**Issue by Goltis** [QuantumBytesInc/RelicsOfAnnorath#10]
When i try to launch the game i get a Message: 

Cant set video mode
D3D11AppWindow::create_context(): required multisample is not supported
Engine::video_restart(): cant set 1920x1080 fullscreen video mode

When i click Ok, the game launches in Windowed mode
I was able to play in fullscreen mode some hours ago

Im using Windows 8.1

**Comment by Goltis** [comment]
reboot didnt fix it, however when i put it to fullscreen in the options after launching in windowed mode it works in fullscreen even with 16x AA

**Comment by ManuelGysin** [comment]
Thanks for the information. We will investigating it future, seems like a bug in our settings implementation.
