### ISSUE TITLE
Segfault in CoherentUI

### ISSUE THREAD

**Issue by ArchangeGabriel** [QuantumBytesInc/RelicsOfAnnorath#12]
When I try to run ROA, it start in a strange windowed mode (note the snapshot resolution, while I’m on a 3200x1800 screen), and then stay on ressource intensive scene with nothing to do (screen below).

![roa](https://cloud.githubusercontent.com/assets/490531/5596645/d64852f0-9293-11e4-9030-cc32e9fe8380.png)

When I look at dmesg, I see this:

```
CoherentUI_Host[24748]: segfault at 0 ip 00007fc19dc2fb2a sp 00007fff3d063d68 error 4 in libc-2.20.so[7fc19dbae000+199000]
CoherentUI_Host[24710]: segfault at 0 ip 0000000000461c9a sp 00007fff62a54990 error 4 in CoherentUI_Host.bin[400000+42f6000]
```

**Comment by ManuelGysin** [comment]
Hello

Can you please tell me which distribution you are using?

**Comment by ArchangeGabriel** [comment]
ArchLinux (and I’m current maintainer of the package there). This happens either with Intel 4600 with OSS driver (which only supports OpenGL 3.3 at this time) and NVIDIA GT750M with proprietary driver (which supports up to OpenGL 4.5).

Note that this might be a bug in primus (the Bumblebee backend), but I can’t compare with VirtualGL since clicking on play doesn’t seem to have any effect.

**Comment by ManuelGysin** [comment]
It's possible that libudev can cause this.
Can you please try the following:

- Start the launcher and login, after everything is good to play do step 2
- in <install dir>\game\lib you find libudev, replace it the your system one
- Hit play

At primus/bumblebee:
This can be possible, the main problem is that the engine calls CoherentUI_Host.bin which is an own executable, maybe there is a context switch and this causes the crash.

Are you familiar with gdb? If yes, can you upload a backtrace?

**Comment by ArchangeGabriel** [comment]
Replacing game/lib/host/libudev.so.0 with my system /usr/lib/libudev.so.1.6.2 did work. Do you need further info? I can try to get a backtrace with gdb tomorrow if you’re still interested.

**Comment by ManuelGysin** [comment]
Perfect, thanks for testing. GDB backtrace is no longer needed. I need to adjust the deployment of the libudev but this gonna take sometime. The idea is to find the system one and link it to the lib folder. But I'm not sure how I can handle this in a generic way for every distribution.

**Comment by ArchangeGabriel** [comment]
I’m not a lib/arch/system expert, but this is going to be a real pain I think.

Here I have:
```
/usr/lib/libudev.so -> libudev.so.1.6.2
/usr/lib/libudev.so.1 -> libudev.so.1.6.2
/usr/lib/libudev.so.1.6.2
```

On amd64 debian:
libudev1 package (Jessie and after):
```
/lib/x86_64-linux-gnu/libudev.so.1
/lib/x86_64-linux-gnu/libudev.so.1.5.0
```
libudev0 package (Wheezy and before):
```
/lib/x86_64-linux-gnu/libudev.so.0
/lib/x86_64-linux-gnu/libudev.so.0.13.0
```

Ubuntu is different. Fedora is different. IMHO, the only way to do this, is to let the packager of each distribution adjust this. But if you find another way, it could be useful for a lot of people I think.

**Comment by ManuelGysin** [comment]
I found this deployment script for coherent libudev, this could work:


```bash
UDEV=lib/x86_64-linux-gnu/libudev.so

function has_ldconfig {
	(which ldconfig && ldconfig -p) > /dev/null
	return $?
}

function check_udev {
	if has_ldconfig
	then
		ldconfig -p | grep libudev.so.0 > /dev/null
	else
		test -e "/$UDEV.0" -o -e "/usr/$UDEV.0"
	fi
	return $?
}

function find_udev {
	if has_ldconfig
	then
		UDEV_SO=`ldconfig -p | grep libudev | sed -e 's/.*=>\s*//'`
	elif [ -e "/$UDEV.1" ]
	then
		UDEV_SO="/$UDEV.1"
	elif [ -e "/usr/$UDEV.1" ]
	then
		UDEV_SO="/usr/$UDEV.1"
	else
		UDEV_SO=''
	fi
	echo "$UDEV_SO"
}

HOST_DIR=`dirname "$0"`
if [ -n "$LD_LIBRARY_PATH" ]
then
	export LD_LIBRARY_PATH="$HOST_DIR":$LD_LIBRARY_PATH
else
	export LD_LIBRARY_PATH="$HOST_DIR"
fi

if ! ( [ -e "$HOST_DIR/libudev.so.0" ] || check_udev )
then
	UDEV_SO=`find_udev`
	if [ -e "$UDEV_SO" ]
	then
		ln -s "$UDEV_SO" "$HOST_DIR/libudev.so.0"
	else
		echo "Could not find libudev."
	fi
fi
```

But in a long shot we need some clear switch to tell the launcher if it is in generic mode (the one from the portal) or in custom mode. If custom mode, we should not download any libraries or do auto updates. This takes some effort and will be a long shot resolution. If you can currently fix the issue within PKG it would be perfect.

**Comment by ArchangeGabriel** [comment]
I can add a ugly fix that would be to symlink the system libudev and then run `chattr +i` on the symlink so that the updater can’t replace it.

**Comment by ArchangeGabriel** [comment]
Hum, actually I can’t chattr a symlink, so I would need to copy the system libudev, but then we might expect issue on libudev updates, right?

**Comment by ArchangeGabriel** [comment]
Oh, never mind, it seems that the launcher can overwrite a wrong libudev file, but not a symlink.

**Comment by ManuelGysin** [comment]
OK,there is still one problem if torrent download method is used. I need a slight redesign of some stuff in the launcher to clean this up. Currently other stuff has more priority, but I try my best to do this in the next weeks.

**Comment by ManuelGysin** [comment]
So, I was lucky and could find a workaround with the torrent. I will address https://github.com/QuantumBytesInc/ROAL/issues/7 too and then commit it to master after QS.

**Comment by ManuelGysin** [comment]
Fixed, QS pending, then pushed to master.
