### ISSUE TITLE
[ROAP] Add German translation for features

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#23]
Translate all features from English to German.
DL: 30.06.2016

**Comment by ManuelGysin** [comment]
Before you begin with the translation, please contact me. There are some special things to know how to translate.

**Comment by Sakubik** [comment]
First draft done.

Now need @ManuelGysin  to read through, correct content.
Then I will re-read to check spelling and grammar.

**Comment by graphefruit** [comment]
Awesome work! Thanks so far
