### ISSUE TITLE
Release new Portal version with fixed SEO/Fixed Images/Fixed JS issues

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#47]
After we had many bugs while crawling the page from google, we needed to change the whole SEO output, image outputs and JavaScript errors.

- [ ] Minify CSS / JavaScript / Cache templates @graphefruit
- [ ] Prepare for release @graphefruit
- [ ] Release @ManuelGysin

**Comment by ManuelGysin** [comment]
Done with v1.2c
