### ISSUE TITLE
Initial migrations (makemigrations)

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#51]
Actual problem: We don't commit the makemigration changes into GIT, because of this we get an inconsistency inside the Database.

We need to revert to "0" and need to create initial migrations for the Database.

Aswell we need to create initial datas aswell @ManuelGysin - I need your help here.

**Comment by graphefruit** [comment]
After discussion: 
We'll make an initial "makemigrations" for all models.
After that we'll add our needed database entries in these migration files.
Because of this we can deploy anywhere and don't need to worry about the data.

Needed file entries will be added in code and referenced. After that they will be published to amazon

**Comment by graphefruit** [comment]
Task will be done until next week.

**Comment by graphefruit** [comment]
We're actualy on this point.
The problem is we encountered circular problems.
Because of this we need to change the model and do multiple migrations to get the state clean then.

**Comment by graphefruit** [comment]
Task is good.
Makemigrations can be executed now, aswell the first datas are created now.

**Comment by ManuelGysin** [comment]
Done and tested.
