### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#53]
Like discussed, we need to evaluate how we could change our css to not just support FULL-HD.
How are images affected, how need to be the ground based css, which changes to we need.

The setup should not be actualy in our environment rather on a test page with images of our GUI.

Special treatments like the bag system needs to be checked aswell.

@rotwurstesser1 @pquantum

**Comment by rotwurstesser1** [comment]
Ideas: SVG or replacing Images on the fly with JS or high-dpi-mediaqueries

**Comment by rotwurstesser1** [comment]
https://css-tricks.com/snippets/css/retina-display-media-query/ idea 1

**Comment by rotwurstesser1** [comment]
Flexbox as solution is smart! mb we need to add retina media queries though
