### ISSUE TITLE
Fix unneeded HTTP-Calls

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#54]
There are many HTTP-Calls which can be avoided, please take a careful look over the whole interface if we realy need to do HTTP-Calls or not.

One sample: FAQ-Detail-Controller did always a HTTP-Request, even if we already had all data.
And therefore we runned into a bug where we called the API 50 times for one FAQ-Call.

@pquantum @rotwurstesser1

**Comment by ManuelGysin** [comment]
This is a very important topic. Doing this request handling the wrong way causes:

- Additional costs for network traffic
- Additional costs for more infrastructure
- Instability

This means we lose money and are operating in a very inefficient way. This is not how it works in these days.

Do your code well designed and test it for multiple side effects. The current quality is leaking all of this.

Additional issues will be assigned to improve this situation.

**Comment by graphefruit** [comment]
@pquantum @rotwurstesser1 Please have a look on our development portal and try to understand the unneeded calls.
E.g.: Everytime I swap an feature image, an HTTP-Call is executed.
When I memorize it correctly you already got all informations which is on page 1 / 2 etc.

Else we can have a look together.
thanks

**Comment by pquantum** [comment]
Closed. Unneeded HTTP-Call fixed on Feature-Detail Slide-Change.
