### ISSUE TITLE
Gather used components

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#56]
# General

Collect all third party libraries and their corresponding license used in all our projects.

Take care of dual licensing libraries.

## Result

Full licence list with all used components.

# Dependencies

## Works

@pquantum @rotwurstesser1  Please do ROAP
@LarsSaalbach Please do ROAG
@TobiasTrabelsi Please do ROAL
@ManuelGysin I think rest part is on your side?

## Modules

- [x] QBB
- [x] QBD
- [x] QBP
- [ ] QBJ
- [x] QBLE
- [x] QBPG
- [x] QBRP
- [X] ROAA
- [X] ROAF
- [X] ROAG
- [ ] ROAJ
- [X] ROAP
- [x] ROAT
- [x] ROAC
- [X] ROAL
- [X] ROAI

# Progress

- [x] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by ManuelGysin** [comment]
Collect all third party libraries and their corresponding license used in all our projects.

Take care of dual licensing libraries.

**Comment by rotwurstesser1** [comment]
ROAP and QBP done

**Comment by ManuelGysin** [comment]
Mainly done, list needs to kept updated.
