### ISSUE TITLE
Implement centralized configuration for django based projects

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#57]
# General

Implement basic settings which are shared between the django projects as python module.

## Result

One centralized  configuration for all django projects.

## Detailed description 

None

# Dependencies

## Modules

- [x] QBD
- [x] QBP
- [x] ROAA
- [x] ROAF
- [x] ROAG
- [x] ROAP
- [x] ROAT

## Operating System

- [x] Windows
- [x] Linux

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [ ] Merged

**Comment by ManuelGysin** [comment]
PR pending on ROAP.

**Comment by ManuelGysin** [comment]
QBP, QBD and ROAA merged.

**Comment by ManuelGysin** [comment]
ROAG merged, awaiting test results.

**Comment by graphefruit** [comment]
I test it on Monday/Tuesday.

**Comment by ManuelGysin** [comment]
ROAF in testing, afterwards we are done.

**Comment by ManuelGysin** [comment]
Deadline CW 17

**Comment by ManuelGysin** [comment]
Done
