### ISSUE TITLE
QBP - News/Team - Changes

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#59]
# General

The actual quantumbytes portal website needs changes for the news-list and team-list sites.

## Result

1. News:
- We don't do an detail view (because we won't have much news on this portal)
- We'll provide the title and text in full format listed.

2. Team:
- The raster view need to be changed from 4 to 3
- Add Sebastian with dummy picture at the moment
- Add a dummy text on each detail view when clicking on picture

## Detailed description 

None

# Dependencies

## Modules

- [ ] QBP

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by ManuelGysin** [comment]
Please update this issue. I think it's solved.
