### ISSUE TITLE
QBP - SEO

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#60]
# General

Like in ROAP we're missing all meta tags for google index

## Result

Add all needed meta tags for all sites with specific and different content.
Because we don't have a news-detail and a team-detail page, we can't provide 'detail'-seo here.

## Detailed description 

@rotwurstesser1 Please help to define which metatags are needed
Actual sample:
```
<title ng-bind="siteTitle +' - Relics of Annorath'" class="ng-binding">About The Game - Relics of Annorath</title>
<meta id="metaDescription" name="description" content="About the game">
<meta content="mmorpg,sandbox,game,gaming,relics of annorath,roa,Merasurien,gathering,crafting,pvp" name="keywords">
<meta content="mmorpg,gaming,game,sandbox" name="page-topic">
<meta content="1 days" name="revisit-after">
<meta content="aFSv5OC-hlQKE0_JIR2m5CN364UDGlqb5h5cXdnhc1w" name="google-site-verification">
<meta id="metaTitle" name="title" content="About the game">
<meta id="metaOgURL" property="og:url" content="https://droap.annorath-game.com/game/">
<meta id="metaOgType" property="og:type" content="Article">
<meta id="metaOgTitle" property="og:title" content="About the game">
<meta id="metaOgDescription" property="og:description" content="About the game">
<meta id="metaOgImage" property="og:image" content="https://s3.amazonaws.com/qb-roap/development/data/static/gui/img/bg_burg.jpg">
<meta content="index, follow" name="robots"><meta content="text/html; charset=utf-8" http-equiv="Content-Type">
```
# Dependencies

## Modules

- [x] QBP

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by rotwurstesser1** [comment]
@ManuelGysin Pascal needs some help from you here, also i need access to google analytics (or a an embed generated by you) so we can add this to the portal!

**Comment by rotwurstesser1** [comment]
Assigned @ManuelGysin  to help @pquantum with connecting the placeholders

**Comment by rotwurstesser1** [comment]
TODO: add analytics account @ManuelGysin

**Comment by ManuelGysin** [comment]
Account added and permission granted.

**Comment by ManuelGysin** [comment]
Done
