### ISSUE TITLE
QBP - Issues

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#63]
# General

Before we can go live we've some issues which needs to be resolved

## Result

All issued resolved.

## Detailed description 

- [x] 1. Contact - Form - Overlapping labels
When navigation back to the contact-form the values still exists and are not overwritten
![image](https://cloud.githubusercontent.com/assets/6260244/23551210/7de92d9a-0015-11e7-972d-fb658d4e6e37.png) @pquantum 
- [x] 2. Contact - Form - Missing Values:
Rename subject to message and replace with a textarea @pquantum  @ManuelGysin 
- [x] 3. Contact - Form - Sending:
When trying to send the contact-form it crashes, URL: https://dqbp.quantum-bytes.com/contactform/
```
Not Found

The requested URL /contactform/ was not found on this server.
``` 
@ManuelGysin 

- [x] 4. Mobile - Menu
When you're smaller then 1150px, the mobile bar should be floating to the right and not attached to the logo
![image](https://cloud.githubusercontent.com/assets/6260244/23551318/3457f85e-0016-11e7-89df-0caaa7af1313.png)

@pquantum 

- [x] 5. SEO
Seo is missing and incorrect. E.g. author should be "QuantumBytes" and not "Quantum Bytes"
See issue: https://github.com/QuantumBytesInc/RelicsOfAnnorath/issues/60
@pquantum  @rotwurstesser1 

- [x] 6. About us: Typo:
QuantumBytes **Inc.was** founded in 2011 in Sunnyvale, California. (Missing space)

- [x] 7. QuantumBytes instead of Quantum Bytes.
Fix all typos with an space inside.

Additional input from @Sakubik :

- [x] Open link in new in new window
- [x] Change _write us a message_ to _send us a message_
- [x] Adjust ROA text
- [x] Replaces pictures
- [x] Add social media buttons in the footer

# Dependencies

## Modules
- [x] QBP

## Operating System
# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by ManuelGysin** [comment]
6 and 7 fixed.

**Comment by ManuelGysin** [comment]
2. We do not need a subject, renamed it to message.

**Comment by rotwurstesser1** [comment]
Mobile is fixed
SEO has a Django problem, would be cool if @ManuelGysin  could help us out this weekend

**Comment by ManuelGysin** [comment]
Could you give me please some details?

**Comment by rotwurstesser1** [comment]
@ManuelGysin i assigned you to SEO which is the main topic of this bug

**Comment by rotwurstesser1** [comment]
Update: Form is completed

**Comment by rotwurstesser1** [comment]
Update: Author is now "QuantumBytes"

**Comment by ManuelGysin** [comment]
Added post view for sending with validation.

**Comment by ManuelGysin** [comment]
Done
