### ISSUE TITLE
Change to Rest-Framework-API

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#64]
# General

Our Website on ROAG is communication with django_ajax, which is part of django and an own module.

## Result

We need to rewrite this communication to fit the REST-Framework-API

## Detailed description 
Particulary affected is the UICommunicate, because all calls are redirected via this service.
So it shouldn't be a to big of a risk to change it.

# Dependencies

## Modules

- [x] ROAG

## Operating System

- [x] Windows
- [x] Linux

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by graphefruit** [comment]
This will be prioritized after the full Knox/token changes.

**Comment by ManuelGysin** [comment]
Current state?

**Comment by graphefruit** [comment]
Changes done. Looks good so far, but needs further testing.

**Comment by graphefruit** [comment]
Refresh fixed. Needs to be tested with launcher now

**Comment by graphefruit** [comment]
Tested with launcher today. 
- Launcher version
- login
- refresh
Working nicely
