### ISSUE TITLE
QBP - Unsupported URL

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#65]
# General

The URL `https://www.quantum-bytes.com/` is working but not `https://quantum-bytes.com/`

## Result

Support the url without `www` aswell.

## Detailed description 

The problem is, that `https://quantum-bytes.com` is present  within the meta-tags, so crawler would have a problem.

# Dependencies

## Modules

- [x] QBP

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by ManuelGysin** [comment]
Metatags fixed, service adjusted to route quantum-bytes.com to www.quantum-bytes.com
