### ISSUE TITLE
Missing SEO-Tags

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#66]
# General

On the main-page all seo-tags are available.
On News-Page e.g. not all seo-tags are available.
This is critical because of the google-crawling.

## Result

Seo-Tags should exists everyhwere
Edit: Please fix the og:url metatag with `https://quantum-bytes.com` to `https://www.quantum-bytes.com`
URL without www is not supported.
@rotwurstesser1 You're lead here please

## Detailed description 

# Dependencies

## Modules

- [ ] QBP

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by ManuelGysin** [comment]
Please specify the needed tags.

**Comment by graphefruit** [comment]
All needed SEO-Tags:
```
<title ng-bind="siteTitle +' - Relics of Annorath'" class="ng-binding">About The Game - Relics of Annorath</title>
<meta id="metaDescription" name="description" content="About the game">
<meta content="mmorpg,sandbox,game,gaming,relics of annorath,roa,Merasurien,gathering,crafting,pvp" name="keywords">
<meta content="mmorpg,gaming,game,sandbox" name="page-topic">
<meta content="1 days" name="revisit-after">
<meta id="metaTitle" name="title" content="About the game">
<meta id="metaOgURL" property="og:url" content="https://www.annorath-game.com/game/">
<meta id="metaOgType" property="og:type" content="Article">
<meta id="metaOgTitle" property="og:title" content="About the game">
<meta id="metaOgDescription" property="og:description" content="About the game">
<meta id="metaOgImage" property="og:image" content="https://dhlufim0x8urs.cloudfront.net/production/data/static/gui/img/bg_burg.jpg">
<meta content="index, follow" name="robots">
<meta content="aFSv5OC-hlQKE0_JIR2m5CN364UDGlqb5h5cXdnhc1w" name="google-site-verification">
```
This Tags are the same on our portal. Please check these seo-tags aswell for the home-page on QBP.

@ManuelGysin  I think you can help with the `google-site-verifcation id for qbp?

**Comment by ManuelGysin** [comment]
@graphefruit We are verified since a long time.

**Comment by graphefruit** [comment]
Removed verification because we're already verified by google

**Comment by pquantum** [comment]
done
