### ISSUE TITLE
Content update

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#68]
# General

Portal needs content update.

## Result

The content is updated and refreshed.

## Detailed description 

Update content analog https://docs.google.com/document/d/142Hb0Rs1wslSeOkoxj6VYpCE220vAQc7Nmyg8BbZgQg/edit#

Some parts are priority high!

# Dependencies

## Modules

- [ ] ROAP

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by Sakubik** [comment]
It is missing @ManuelGysin ... as we never got to talk about the list we made and approved what should or shouldn't be realised in what way.

**Comment by ManuelGysin** [comment]
We will start to select every week two - four bullets on the list to implement. We are going the easy way, everything we can adjust quickly we choose first.

**Comment by ManuelGysin** [comment]
Work will start after ComicCon. Weekly issues will be created.
