### ISSUE TITLE
QBP - Broken team image

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#69]
# General

The image of team is broken
![image](https://cloud.githubusercontent.com/assets/6260244/23768640/fed3b820-050c-11e7-8e20-fe910b236d55.png)

## Result

Fixing the overlay.
## Detailed description 

# Dependencies

## Modules

- [ ] QBP

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by pquantum** [comment]
done
