### ISSUE TITLE
Adopt newest captcha

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#71]
# General

Using the Invisible recaptcha. 

## Result

Better user experience. 

## Detailed description 

https://developers.google.com/recaptcha/docs/invisible

# Dependencies

## Modules

- [x] ROAP
- [x] ROAA

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by graphefruit** [comment]
Roap ist affected with this captcha aswell

**Comment by ManuelGysin** [comment]
In fact, only ROAP.

**Comment by graphefruit** [comment]
On ROAA theres a captcha aswell when you want to recover your password

**Comment by ManuelGysin** [comment]
Done

**Comment by graphefruit** [comment]
@ManuelGysin  shouldn't this affect ROAP aswell - There is the normal recaptcha implemented by registration

**Comment by graphefruit** [comment]
Reopend @pquantum Please do this on ROAP aswell

**Comment by rotwurstesser1** [comment]
@pquantum bump

**Comment by ManuelGysin** [comment]
@pquantum Update this issue.

**Comment by graphefruit** [comment]
Done today. Needs to be tested in other browsers

**Comment by graphefruit** [comment]
Captcha is checked on server aswell now.

**Comment by graphefruit** [comment]
Created pull request, please review and merge.
If needed add the secret key of google to the environment.

Edge, Chrome, FireFox aswell as Google Android worked on my side.

**Comment by graphefruit** [comment]
Testing in progress, actualy one little bug open which will be deployed today

**Comment by graphefruit** [comment]
Merged and released. Closed
