### ISSUE TITLE
Launcher needs timeout on json requests

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#72]
# General

If a json request takes to long or something goes wrong, we need a slot to communicate this to the source caller.

## Result

Stability.

## Detailed description 

N/A

# Dependencies

## Modules

- [ ] ROAL

## Operating System

- [x] Windows
- [x] Linux

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by graphefruit** [comment]
@TobiasTrabelsi  Do I need to provide something on ROAG for ROAL?

**Comment by TobiasTrabelsi** [comment]
I don't think so. I just have to find the time to work on this

**Comment by Lerentis** [comment]
Done with [5101720](https://github.com/QuantumBytesInc/ROAL/commit/51017206db63ddb5c7aa48bd89de8583da24ab96)
