### ISSUE TITLE
Redesign roal/roag communication

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#73]
# General

Currently there is a gap with the communication between roal and roag. This needs a rewrite of some code parts on both sides.

## Result

The API for JSON request is well designed and ROAL and ROAG can communication with each other.

## Detailed description 

We currently have the following API-Points:

- /login
- /logout
- /request which needs authentication

Like mentioned above the request end point needs an authorized call. Currently the launcher does a version check on startup, which is redirected to /request, because we are not logged-in at this stage, this call will never work.

So we need first an additional end point: /launcher

Code affected:

- https://github.com/QuantumBytesInc/ROAL/blob/testing/src/cpp/httpupdate.cpp#L161

We also have some logical error in the code path:

Currently we depend on the configuration class to save the authentication token, but this class is never initialized because a successfully call needs an authenticated request to /request. This needs the token, but the token needs first the configuration. This will crash the launcher and/or an endless waiting loop.

The workflow must be:

1. Version check to /launcher
2. Login to /login
3. Every other request to /request
4. Logout to /logout

Because of the changes I propose the following additional changes:

1. /launcher can be used as logging end point for non authorized requests
2. /request can be used as logging end point for authorized requests

Additional:

For a clear separation of information, we do not save the token in the configuration class. This only cause troubles and is the wrong place for it. In fact the token is used in the following use cases:

- Any json request which needs to be authenticated
- The game process

I suggest we keep  the token in JsonRequest and do a JsonRequest::getToken() before we enter the game process.

# Dependencies

## Modules

- [x] ROAG
- [x] ROAL

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by ManuelGysin** [comment]
Please provide feedback.

**Comment by graphefruit** [comment]
launcher call will be provided till tomorrow.
After this tobi can check.

**Comment by graphefruit** [comment]
@TobiasTrabelsi  /launcher/ request can now be done. 

Sample call: 
```
echo '{"CALLER":5, "ACTION":0 }' | http -v POST https://droag.annorath-game.com/interface/launcher/"
```
Please make sure you send the launcher key and action key aswell.
Maybe we want to expand this call later on for the launcher

**Comment by ManuelGysin** [comment]
@graphefruit @Lerentis Coordinate a meeting with me so we can close this.

**Comment by Lerentis** [comment]
created doodle poll. meeting will occurs within a week

**Comment by Lerentis** [comment]
Done and Commited to Testing [f631ba0](https://github.com/QuantumBytesInc/ROAL/commit/f631ba05d71857b2050e4cf72435e75a8bba7d6a)
