### ISSUE TITLE
Adjust YouTube link

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#74]
# General

Adjust the Youtube link on the social media bar. 

## Result

The buttons points to https://m.youtube.com/channel/UCAsmV-UgJhIbK6PlPY0QaXQ

## Detailed description 

N/A

# Dependencies

## Modules

- [ ] ROAP

## Operating System

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by rotwurstesser1** [comment]
changed on dev
