### ISSUE TITLE
Account recovery error

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#75]
# General

When you recover your account and try to change to new password, the server generates and error.

## Result

No error, successfully generated email

## Detailed description 

Thrown error:
```
recovery_done_text_body % (user.username, settings.BASE_URL, settings.PORTAL_URL),
TypeError: not all arguments converted during string formatting
```

# Dependencies

## Modules

- [ ] ROAA

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by graphefruit** [comment]
Prio to high, because just email is crashing, you can login with the new password

**Comment by ManuelGysin** [comment]
Hotfix deployed, please test.

**Comment by graphefruit** [comment]
LGTM. Closed. 
Thank you!
