### ISSUE TITLE
Google index fuckuped

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#76]
# General

https://www.google.ch/#q=site:www.annorath-game.com&start=0&*

## Result

https://www.google.ch/#q=site:www.annorath-game.com&start=0&* will work correctly.

## Detailed description 

https://www.google.ch/#q=site:www.annorath-game.com&start=0&*

Everything is wrong indexed.

# Dependencies

## Modules

- [x] ROAP

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by graphefruit** [comment]
I've searched a bit around on google.
I need to check if its maybe working when setting html5-provider to true and adding a "#" for the urls.

If this is not working, we should do it like we did it with facebook, send the crawler to the django request and prepare the content in the code behind.

I didn't find any more information about problems while indexing with google and angularjs else.

**Comment by ManuelGysin** [comment]
QuantumBytesInc/ROAP/releases/tag/v1.3f

First try to solve this, sitemap has been adjusted.

**Comment by ManuelGysin** [comment]
Fixed with prerender.
