### ISSUE TITLE
Exception email cant be sent

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#77]
# General

When registering a new user, an e-mail cant be sent to him, and therefore the registrations runs into an error, but the user is created and saved.

## Result

E-Mail will be sent again.

## Detailed description 
ROAA-Development log console.
`BotoServerError: 403 Forbidden <ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/"> <Error> <Type>Sender</Type> <Code>MissingAuthentication....`

# Dependencies

## Modules
- [ ] ROAA

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by ManuelGysin** [comment]
Please retest.

**Comment by graphefruit** [comment]
@ManuelGysin still the MissingAuthentication error

**Comment by ManuelGysin** [comment]
Fixed
