### ISSUE TITLE
Add Let's Encrypt Certificate to ROAL

### ISSUE THREAD

**Issue by Lerentis** [QuantumBytesInc/RelicsOfAnnorath#78]
# General

As all our Services are now validated via Let's Encrypt, we have to add the Let's Encrypt Certificate to ROAL as well. 
The current ssl config will result in a failure 

## Result

Valid TLS connection ROAL/ROAL <--> DROAG

## Detailed description 

Provide new pem Certificates to ship with ROAL

# Dependencies

## Modules

- [ ] QBB
- [ ] QBD
- [ ] QBP
- [ ] QBJ
- [ ] QBLE
- [ ] QBPG
- [ ] QBRP
- [ ] ROAA
- [ ] ROAF
- [ ] ROAG
- [ ] ROAJ
- [ ] ROAP
- [ ] ROAT
- [ ] ROAC
- [x] ROAL
- [x] ROAI

## Operating System

- [x] Windows
- [x] Linux

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by ManuelGysin** [comment]
Done
