### ISSUE TITLE
Update applications

### ISSUE THREAD

**Issue by ManuelGysin** [QuantumBytesInc/RelicsOfAnnorath#79]
# General

Update all containers.

## Result

All updates are installed.

# Dependencies

## Modules

- [x] QBB
- [x] QBD
- [x] QBP
- [x] QBJ
- [x] QBPG
- [x] QBRP
- [x] ROAA
- [x] ROAF
- [x] ROAG
- [x] ROAP
- [x] ROAT

# Progress

- [x] Define and create test sequences
- [x] Implemented task
- [x] Verify result with test sequences
- [x] Pull request
- [x] Merged

**Comment by ManuelGysin** [comment]
@graphefruit Please prepare GULP for ROAP-PRD

**Comment by graphefruit** [comment]
I'll, I just need to test the other browsers and delete some obsolete files.

**Comment by graphefruit** [comment]
@ManuelGysin can you please add the google captcha secret key to the environment? `base.py` ROAP

**Comment by graphefruit** [comment]
I think this is fixed or? @Manuel
