### ISSUE TITLE
Add Rodrigo to Teampage

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#80]
# General

After Rodrigo joining our team, he needs to be added on our https://www.quantum-bytes.com/team/ page aswell.

## Result

Image and description available with rodrigo 

## Detailed description 
I've sent you the email with the image of rodrigo to add, please make it fit.
Title: Engineer - C++
Description: "C++ engine hacker" 

# Dependencies

## Modules

- [ ] QBP

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by pquantum** [comment]
There seems to be a problem in the QBP Django CMS backend. (see screenshot)
The UI of Django is displayed without any CSS formatting.
I cannot add another team member until this is fixed.

![django_problem](https://cloud.githubusercontent.com/assets/14222522/26072022/65234be6-39aa-11e7-8817-dda73c9d4459.PNG)


Here is the image of Rodrigo for adding to the website later on:
![rodrigo](https://cloud.githubusercontent.com/assets/14222522/26072097/afdf6462-39aa-11e7-8bba-34cc878e9b2f.png)

**Comment by graphefruit** [comment]
@ManuelGysin can you have a look here?
@pquantum thanks so far

**Comment by pquantum** [comment]
Rodrigo was added to the team page. 
@graphefruit Can you tell me his last name so I can complete his name.

**Comment by graphefruit** [comment]
@pquantum  Rodrigo Boratto

**Comment by pquantum** [comment]
Ok, changed his name.
@ManuelGysin needs to be merged into master branch.

**Comment by ManuelGysin** [comment]
merged

**Comment by ManuelGysin** [comment]
Published
