### ISSUE TITLE
Gulp task / SQLLite / Translation

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#82]
# General

After we've fixed the general gulp problem with drone we've three more situations, cause of clairty I've closed the old one and opend a new task.

## Result

Fixing this three more situations

## Detailed description 
- When a new master release is created with a tag, drone needs to grab the task and build for master
  - Affects ROAG / ROAP
- .SQLLite needs to be generated and transferred to `/static/gui/sqllite/*.sqllite`
- Translation file needs to be generated and transferred  to `/source/static/*.js` - Path may be changed
  - This translation file needs to be generated before the gulp task runs because it will be put into the minification aswell

# Dependencies

## Modules

- [x] ROAG
- [ ] ROAP

## Operating System

- [ ] Windows
- [ ] Linux

# Progress

- [ ] Define and create test sequences
- [ ] Implemented task
- [ ] Verify result with test sequences
- [ ] Pull request
- [ ] Merged

**Comment by ManuelGysin** [comment]
Done
